//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopRussionsRoads.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Start { get; set; }
        public int MakerID { get; set; }
        public string Description { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
